import 'package:flutter/material.dart';

class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'es': {
      'dashboard_title': 'San José Dashboard',
      'planning': 'Planning',
      'guardias': 'Guardias',
      'departamentos': 'Departamentos',
      'profesores': 'Profesores',
      'ajustes': 'Ajustes',
      'salir': 'Salir',
      'inicio': 'Inicio',
      'ausencias_hoy': 'Ausencias hoy',
      'pendientes': 'Pendientes',
      'areas': 'Áreas',
      'dptos_personal': 'Departamentos y Personal',
      'privacy_security': 'Privacidad y Seguridad',
      'personalization': 'Personalización',
      'privacy': 'Privacidad',
      'language': 'Idioma',
      'language_desc': 'Cambiar idioma de la aplicación',
      'theme': 'Tema',
      'theme_desc': 'Elige el modo claro, oscuro o del sistema',
      'theme_light': 'Claro',
      'theme_dark': 'Oscuro',
      'theme_system': 'Sistema',
      'change_password': 'Cambiar contraseña',
      'admin': 'Administrador',
      'horarios': 'Horarios',
      'privacy_title': 'PRIVACIDAD Y DATOS',
      'clear_notifications': 'Eliminar notificaciones',
      'clear_notifications_desc':
          'Borra el historial de avisos locales y libera espacio.',
      'clear_notifications_confirm_title': '¿Eliminar notificaciones?',
      'clear_notifications_confirm_content':
          'Se borrarán todos los avisos y mensajes del historial local.',
      'cancel': 'Cancelar',
      'delete': 'Eliminar',
      'notifications_cleared': 'Notificaciones eliminadas',
      'spanish': 'Español',
      'english': 'English',
      'profile_info_title': 'INFORMACIÓN PROFESIONAL',
      'no_session': 'No hay sesión iniciada',
      'teacher_of': 'Profesor de',
      'department': 'Departamento',
      'teaching_schedule': 'Horario Lectivo',
      'assigned_group': 'Grupo Asignado',
      'usual_room': 'Aula Habitual',
      'tutoring': 'Curso/Tutoría',
      'current_status': 'Estado actual',
      'absent': 'Ausente',
      'present': 'Presente',
      'logout': 'Cerrar Sesión',
      'grupos': 'Grupos',
      'asignaturas': 'Asignaturas',
      'aulas': 'Aulas',
      'gestion_prof': 'Gestión Prof.',
      'importar_csv': 'Importar CSV',
    },
    'en': {
      'dashboard_title': 'San José Dashboard',
      'planning': 'Planning',
      'guardias': 'On Call',
      'departamentos': 'Departments',
      'profesores': 'Teachers',
      'ajustes': 'Settings',
      'salir': 'Logout',
      'inicio': 'Home',
      'ausencias_hoy': 'Absences today',
      'pendientes': 'Pending',
      'areas': 'Areas',
      'dptos_personal': 'Departments & Staff',
      'privacy_security': 'Privacy & Security',
      'personalization': 'Personalization',
      'privacy': 'Privacy',
      'language': 'Language',
      'language_desc': 'Change application language',
      'theme': 'Theme',
      'theme_desc': 'Choose light, dark, or system mode',
      'theme_light': 'Light',
      'theme_dark': 'Dark',
      'theme_system': 'System',
      'change_password': 'Change password',
      'admin': 'Admin',
      'horarios': 'Schedules',
      'privacy_title': 'PRIVACY & DATA',
      'clear_notifications': 'Clear Notifications',
      'clear_notifications_desc':
          'Clear local notification history and free up space.',
      'clear_notifications_confirm_title': 'Clear notifications?',
      'clear_notifications_confirm_content':
          'All local notifications and messages will be deleted.',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'notifications_cleared': 'Notifications cleared',
      'spanish': 'Spanish',
      'english': 'English',
      'profile_info_title': 'PROFESSIONAL INFORMATION',
      'no_session': 'No active session',
      'teacher_of': 'Teacher of',
      'department': 'Department',
      'teaching_schedule': 'Teaching Schedule',
      'assigned_group': 'Assigned Group',
      'usual_room': 'Usual Room',
      'tutoring': 'Course/Tutoring',
      'current_status': 'Current Status',
      'absent': 'Absent',
      'present': 'Present',
      'logout': 'Logout',
      'grupos': 'Groups',
      'asignaturas': 'Subjects',
      'aulas': 'Rooms',
      'gestion_prof': 'Staff Mgmt',
      'importar_csv': 'Import CSV',
    },
  };

  static String get(BuildContext context, String key) {
    final locale = Localizations.localeOf(context).languageCode;
    return _localizedValues[locale]?[key] ??
        _localizedValues['es']?[key] ??
        key;
  }
}
