// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLZCY7Xs6qEqOPX6Cwl_EGoAR0QBL8xow',
    appId: '1:799534823523:web:61fb8f230e30943434e056',
    messagingSenderId: '799534823523',
    projectId: 'guardiasapp-495508-61b85',
    authDomain: 'guardiasapp-495508-61b85.firebaseapp.com',
    storageBucket: 'guardiasapp-495508-61b85.firebasestorage.app',
    measurementId: 'G-39YECYSX6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA7JxLuVpXF7x6b5ANOSQ-gtHBXHxF66k',
    appId: '1:799534823523:android:e4450f1a09eedabf34e056',
    messagingSenderId: '799534823523',
    projectId: 'guardiasapp-495508-61b85',
    storageBucket: 'guardiasapp-495508-61b85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq2JH0gEQhz68H8kuFYbuLbXFvXa-NumQ',
    appId: '1:799534823523:ios:55f09cc72aad965f34e056',
    messagingSenderId: '799534823523',
    projectId: 'guardiasapp-495508-61b85',
    storageBucket: 'guardiasapp-495508-61b85.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq2JH0gEQhz68H8kuFYbuLbXFvXa-NumQ',
    appId: '1:799534823523:ios:55f09cc72aad965f34e056',
    messagingSenderId: '799534823523',
    projectId: 'guardiasapp-495508-61b85',
    storageBucket: 'guardiasapp-495508-61b85.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLZCY7Xs6qEqOPX6Cwl_EGoAR0QBL8xow',
    appId: '1:799534823523:web:425461b4cfd54df434e056',
    messagingSenderId: '799534823523',
    projectId: 'guardiasapp-495508-61b85',
    authDomain: 'guardiasapp-495508-61b85.firebaseapp.com',
    storageBucket: 'guardiasapp-495508-61b85.firebasestorage.app',
    measurementId: 'G-1EM387KMY5',
  );
}
